
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import static java.util.Collections.list;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static javax.swing.text.html.HTML.Tag.SELECT;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class DATABASE extends javax.swing.JFrame {

  Connection conn = null;   
PreparedStatement pst = null;
    PreparedStatement pst1 = null;
ResultSet rs = null;
    public DATABASE() {
        initComponents();
        Connect();
       
    }
    public void Connect(){
    try {
        Class.forName("com.mysql.jdbc.Driver");
        try{
            conn = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/simple_student","root","");
                  String sql = "SELECT id AS 'ID', studentname AS 'Student Name',fathername AS 'Father Name',phone AS 'Cellphone Number',dateofbirth AS 'Date Of Birth',gender AS 'Gender',course AS 'Course',year AS 'Year',admissiondate AS 'Admission Date', lrn AS 'LRN',email AS 'Email Address',address AS 'Address'  FROM student";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            studenttable.setModel(DbUtils.resultSetToTableModel(rs));
             studenttable.removeColumn(studenttable.getColumnModel().getColumn(0));
        }catch(SQLException ex){
            Logger.getLogger(SIMPLE_STUDENT.class.getName()).log(Level.SEVERE,null,ex);
        }
    } catch(ClassNotFoundException ex){
        Logger.getLogger(SIMPLE_STUDENT.class.getName()).log(Level.SEVERE,null,ex);
    }
}
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        studenttable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dbirth = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        lrn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pnum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        course = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        admissiond = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        idtxt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("STUDENT REGISTRATION DATABASE");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/icons8-go-back-16.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        studenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Student Name", "Father's Name", "Cellphone #", "Date of Birth", "Gender", "Course", "Year", "Admission Date", "LRN", "Email", "Address"
            }
        ));
        studenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studenttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studenttable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 914, 200));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 35));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, 35));
        jPanel2.add(dbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 115, 28));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Date of Birth:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        lrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lrnActionPerformed(evt);
            }
        });
        lrn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lrnKeyTyped(evt);
            }
        });
        jPanel2.add(lrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 119, 28));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("LRN: ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel2.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 163, 61));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Address:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 119, 28));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Email Address:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Student Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        sname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameActionPerformed(evt);
            }
        });
        jPanel2.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 119, 28));

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel2.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 119, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Father's Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        pnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumActionPerformed(evt);
            }
        });
        pnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnumKeyTyped(evt);
            }
        });
        jPanel2.add(pnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 119, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cellphone Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT GENDER", "MALE", "FEMALE" }));
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 119, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Gender:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT COURSE", "BSIT", "CRIMINILOGY", "EDUCATION", "PSYCHOLOGY", "SOCIAL WORK", "BUSINESS ADMINISTRATION", "AGRICULTURE" }));
        jPanel2.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 119, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Course:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT YEAR", "1ST", "2ND", "3RD", "4TH" }));
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 119, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Year:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));
        jPanel2.add(admissiond, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 115, 31));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Admission Date:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 115, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 760, 260));
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("SEARCH:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 57, 25));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 184, 27));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SIMPLE_STUDENT db = new SIMPLE_STUDENT();
       db.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = DBConnection.getConnection();
          
       
    }//GEN-LAST:event_formWindowOpened

    private void studenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studenttableMouseClicked

      try {
           DefaultTableModel model=(DefaultTableModel) studenttable.getModel();
int selectedRowIndex=studenttable.getSelectedRow();
          Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectedRowIndex, 4).toString());
           Date datee = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectedRowIndex, 8).toString());
          idtxt.setText(model.getValueAt(selectedRowIndex, 0).toString());
sname.setText(model.getValueAt(selectedRowIndex, 1).toString());
fname.setText(model.getValueAt(selectedRowIndex, 2).toString());
pnum.setText(model.getValueAt(selectedRowIndex, 3).toString());
dbirth.setDate(date);
gender.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
course.setSelectedItem(model.getValueAt(selectedRowIndex, 6).toString());
year.setSelectedItem(model.getValueAt(selectedRowIndex, 7).toString());
admissiond.setDate(datee);
lrn.setText(model.getValueAt(selectedRowIndex, 9).toString());
email.setText(model.getValueAt(selectedRowIndex, 10).toString());
address.setText(model.getValueAt(selectedRowIndex, 11).toString());

  
      } catch (ParseException ex) {
          Logger.getLogger(DATABASE.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_studenttableMouseClicked

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped

    }//GEN-LAST:event_searchKeyTyped

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
try {
    String a = "%"+search.getText()+"%";
   
    String sql = "SELECT id AS 'ID', studentname AS 'Student Name',fathername AS 'Father Name',phone AS 'Cellphone Number',dateofbirth AS 'Date Of Birth',gender AS 'Gender',course AS 'Course',year AS 'Year',admissiondate AS 'Admission Date', lrn AS 'LRN',email AS 'Email Address',address AS 'Address'  FROM student WHERE id LIKE'" + a+"' OR studentname LIKE'" + a+"' OR fathername LIKE'" + a+"' OR phone LIKE'" + a+"' OR dateofbirth LIKE'" + a+"' OR gender LIKE'" + a+"' OR year LIKE'" + a+"' OR course LIKE'" + a+"' OR admissiondate LIKE'" + a+"' OR lrn LIKE'" + a+"' OR email LIKE'" + a+"' OR address LIKE'" + a+"'";
pst = conn.prepareStatement(sql);
rs = pst.executeQuery();
studenttable.setModel(DbUtils.resultSetToTableModel(rs));
 studenttable.removeColumn(studenttable.getColumnModel().getColumn(0));
} catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
    }//GEN-LAST:event_searchKeyReleased

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void snameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void pnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnumActionPerformed

    private void lrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lrnActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      update();
         Connect();
           idtxt.setText("");
             sname.setText("");
     fname.setText("");
     pnum.setText("");
     dbirth.setDate(null);
     gender.setSelectedItem("SELECT GENDER");
     course.setSelectedItem("SELECT COURSE");
     year.setSelectedItem("SELECT YEAR");
    lrn.setText("");
     admissiond.setDate(null);
     email.setText("");
     address.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      delete();
      Connect();
       idtxt.setText("");
             sname.setText("");
     fname.setText("");
     pnum.setText("");
     dbirth.setDate(null);
     gender.setSelectedItem("SELECT GENDER");
     course.setSelectedItem("SELECT COURSE");
     year.setSelectedItem("SELECT YEAR");
    lrn.setText("");
     admissiond.setDate(null);
     email.setText("");
     address.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnumKeyTyped
    char vchar = evt.getKeyChar();
           char bchar = evt.getKeyChar();
if(!(Character.isDigit(vchar))){
evt.consume();
}
    }//GEN-LAST:event_pnumKeyTyped

    private void lrnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lrnKeyTyped
     char vchar = evt.getKeyChar();
           char bchar = evt.getKeyChar();
if(!(Character.isDigit(vchar))){
evt.consume();
}
    }//GEN-LAST:event_lrnKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DATABASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DATABASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DATABASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DATABASE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DATABASE().setVisible(true);
            }
        });
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private com.toedter.calendar.JDateChooser admissiond;
    private javax.swing.JComboBox course;
    private com.toedter.calendar.JDateChooser dbirth;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox gender;
    private javax.swing.JLabel idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lrn;
    private javax.swing.JTextField pnum;
    private javax.swing.JTextField search;
    private javax.swing.JTextField sname;
    private javax.swing.JTable studenttable;
    private javax.swing.JComboBox year;
    // End of variables declaration//GEN-END:variables
private void update(){
    try{
          Date a,b,c,d;
a = dbirth.getDate();
c = new java.sql.Date(a.getTime());
b = admissiond.getDate();
d= new java.sql.Date(b.getTime());
   
     String one = idtxt.getText();
     String oneone= sname.getText();
    String two = fname.getText();
    String three = pnum.getText();
    String four = c.toString();
    String five = (String) gender.getSelectedItem();
    String six = (String)course.getSelectedItem();
     String seven = (String)year.getSelectedItem();
   String eight =  d.toString();
   String nine =lrn.getText();
           String ten = email.getText();
                   String eleven =address.getText();
   if (one.equals("")||oneone.equals("")||two.equals("")||three.equals("")||four.equals("")||five.equals("SELECT GENDER")||six.equals("SELECT COURSE")
           ||seven.equals("SELECT YEAR")||eight.equals("")||nine.equals("")||ten.equals("")||eleven.equals("")){
       JOptionPane.showMessageDialog(null, "SOME FIELDS ARE EMPTY");
   }else{
     
        String sql="UPDATE student SET id = ?,studentname=?, fathername=?, phone=?, dateofbirth=?, gender=?, course=?, year=?, admissiondate=?, lrn=?,email=?,address=? WHERE ID = '"+idtxt.getText()+"'";
  
   pst = conn.prepareStatement(sql);
   pst.setString(1,idtxt.getText());
   pst.setString(2,sname.getText());
   pst.setString(3,fname.getText());
   pst.setString(4,pnum.getText());  
   pst.setString(5,c.toString());
   pst.setString(6,(String)gender.getSelectedItem());
   pst.setString(7,(String)course.getSelectedItem());
   pst.setString(8,(String)year.getSelectedItem());
   pst.setString(9,d.toString());
    pst.setString(10,(String)lrn.getText());
     pst.setString(11,(String)email.getText());
      pst.setString(12,(String)address.getText());
       pst.execute();
        JOptionPane.showMessageDialog(null, "Student's Data Updated Successfully");
   } }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, e);
    }
}
private void delete(){
         try{
        String sql = "SELECT * FROM student WHERE id='"+idtxt.getText()+"'";
         pst = conn.prepareStatement(sql);
         rs=pst.executeQuery();
         if (rs.next()){
             String sql2 = "DELETE FROM student WHERE id='"+idtxt.getText()+"'";
               pst = conn.prepareStatement(sql2);
             pst.execute();
             JOptionPane.showMessageDialog(null, "Student's Data Deleted");
         }else{
             JOptionPane.showMessageDialog(null, "No Existing Data");
         }
    }catch(Exception e){
       
}
}
}
